{% set name = "libsharedlibpp" %}
{% set version = "0.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ami-iit/sharedlibpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ae550740d752871dd3ec3930259f7cf273ac2d6b728dbcb05dfc750162dc73dd

build:
  number: 0
  run_exports:
    # See upstream versioning policy in https://github.com/ami-iit/sharedlibpp?tab=readme-ov-file#versioning-policy
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    - ycm-cmake-modules

test:
  commands:
    - test -f ${PREFIX}/include/sharedlibpp/SharedLibraryClassFactory.h  # [not win]
    - test -f ${PREFIX}/lib/libsharedlibpp${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\include\\sharedlibpp\\SharedLibraryClassFactory.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\sharedlibpp.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\sharedlibpp.dll exit 1  # [win]
    - cmake-package-check sharedlibpp
  requires:
    - cmake-package-check
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/ami-iit/sharedlibpp
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Tiny cross-platform plug-in system (dll, so, dylib).

extra:
  feedstock-name: sharedlibpp
  recipe-maintainers:
    - traversaro
